package fr.umlv.javanotebook.exercice;

import org.parboiled.common.FileUtils;
import org.pegdown.Extensions;
import org.pegdown.PegDownProcessor;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.lang.reflect.Method;
import java.util.Objects;

/**
 * this class implement an Exercise with his number and his respons.
 */
class Exercise {

    private final Class<?> respons;
    private final String number;

    Exercise(String number, Class<?> respons) {
        this.number = Objects.requireNonNull(number);
        this.respons = Objects.requireNonNull(respons);
    }

    private static String generateHtml(char[] markdown) {
        PegDownProcessor processor = new PegDownProcessor(Extensions.ALL);
        return processor.markdownToHtml(markdown);
    }

    /**
     * Parses the markdown file and returns the html code generated by the
     * PegDown processor
     *
     * @return returns the html code generated by the PegDown processor
     */
    String toWeb() {
        String fichier = "./exercice/" + number + ".md";
        InputStream input;
        try {
            input = new FileInputStream(fichier);
        } catch (FileNotFoundException e) {
            return "<p>There is no Exercice " + number + "</p>";
        }
        return generateHtml(FileUtils.readAllChars(input));
    }

    Method[] getRespons() {
        return respons.getMethods();
    }

    String getNumero() {
        return number;
    }
}
