package fr.umlv.javanotebook.exercice;

import org.parboiled.common.FileUtils;
import org.pegdown.Extensions;
import org.pegdown.PegDownProcessor;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * this class implement an Exercise with his number and his respons.
 */
class Exercise {

    private final List<Method> respons;
    private final String number;

    private Exercise(String number, List<Method> respons) {
        this.number = Objects.requireNonNull(number);
        this.respons = Objects.requireNonNull(respons);
    }


    public static Exercise create_Exercise(String number, Class<?> class_test_respons) {
        return new Exercise(number, filter(number, class_test_respons));
    }


    private static List<Method> filter(String number, Class<?> class_test_respons) {
        List<Method> tempo = new ArrayList<>();
        for (Method m : class_test_respons.getMethods()) {
            if (m.getName().startsWith("test_" + number)) {
                tempo.add(m);
            }
        }
        return tempo;
    }

    private static String generateHtml(char[] markdown) {
        PegDownProcessor processor = new PegDownProcessor(Extensions.ALL);
        return processor.markdownToHtml(markdown);
    }

    /**
     * Parses the markdown file and returns the html code generated by the
     * PegDown processor
     *
     * @return returns the html code generated by the PegDown processor
     */
    String toWeb() {
        String fichier = "./exercice/" + number + ".md";
        InputStream input;
        try {
            input = new FileInputStream(fichier);
        } catch (FileNotFoundException e) {
            return "<p>There is no Exercice " + number + "</p>";
        }
        return generateHtml(FileUtils.readAllChars(input));
    }

    List<Method> getRespons() {
        return respons;
    }

    String getNumero() {
        return number;
    }
}
