package fr.umlv.javanotebook.exercice;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import org.parboiled.common.FileUtils;
import org.parboiled.common.Preconditions;
import org.pegdown.Extensions;
import org.pegdown.PegDownProcessor;

public class ExerciceParser {

	/**
	 * 
	 * @param name : name of the exercise parsed 
	 * @return returns the html code generated by the PegDown processor
	 */
	public static String toWeb(String name) {
		String fichier = "./exercice/"+name;
		InputStream input = null;
		try {
			input = new FileInputStream(fichier);
		} catch (FileNotFoundException e) {
			System.err.println(e);			
		}    	
		char[] markdown = FileUtils.readAllChars(input);
		Preconditions.checkNotNull(markdown, "The specified file isn't found - "+fichier);
		return generateHtml(markdown);
	}

	private static String generateHtml(char[] markdown) {
		PegDownProcessor processor = new PegDownProcessor(Extensions.ALL);
		String html_code=processor.markdownToHtml(markdown);
		return html_code;
	}
}
